title: Zilin Zhan (詹紫琳)
position: Ph.D. Candidate
affiliation: Beijing Jiaotong University, Beijing, China
email: zilinzhan1@bjtu.edu.cn 
email_link: mailto:zilinzhan1@bjtu.edu.cn 
github_link: 
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
remote_theme: yaoyao-liu/strata-academic
