title: Zilin Zhan (詹紫琳)
position: Ph.D. Candidate
affiliation: Beijing Jiaotong University.<br>No.3 Shangyuancun, Haidian District, Beijing, China
email: 
email_link: mailto:zilinzhan@bjtu.edu.cn
github_link: https://github.com/Zilinzhan
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png
description: A second-year PhD candidate at Beijing Jiaotong University (BJTU)
remote_theme: yaoyao-liu/strata-academic
